import React, { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import api from '../../../api/axios';
import toast from 'react-hot-toast';
import { Sparkles, Send, Mail } from 'lucide-react';

const InvitationTab = ({ meeting }) => {
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [isPreview, setIsPreview] = useState(false);
  
  const queryClient = useQueryClient();

  const generateMutation = useMutation({
    mutationFn: async () => {
      const { data } = await api.get(`/ai/meetings/${meeting.id}/generate-invite`);
      return data;
    },
    onSuccess: (data) => {
      setSubject(data.subject);
      setBody(data.body);
      toast.success('Invitation generated by Gemini AI!');
    },
    onError: () => toast.error('Failed to generate invitation')
  });

  const sendMutation = useMutation({
    mutationFn: async (payload) => {
      const { data } = await api.post(`/ai/meetings/${meeting.id}/send-invites`, payload);
      return data;
    },
    onSuccess: (data) => {
      toast.success(data.message || 'Invitations sent successfully');
      queryClient.invalidateQueries(['meeting', meeting.id]);
    },
    onError: () => toast.error('Failed to send invitations')
  });

  const handleSend = () => {
    if (!subject || !body) return toast.error('Subject and body are required');
    if (window.confirm(`Are you sure you want to send this to ${meeting.members?.length || 0} members?`)) {
      sendMutation.mutate({ subject, body });
    }
  };

  return (
    <div className="p-6 bg-white rounded-b-xl border border-t-0 border-slate-200">
      
      <div className="flex justify-between items-center mb-6">
        <div>
          <h3 className="font-semibold text-lg text-slate-800">Email Invitations</h3>
          <p className="text-sm text-slate-500">Generate a professional invitation using AI, then broadcast to all imported members.</p>
        </div>
        <button 
          onClick={() => generateMutation.mutate()}
          disabled={generateMutation.isLoading}
          className="flex items-center space-x-2 bg-indigo-600 text-white px-4 py-2 rounded-lg font-medium text-sm hover:bg-indigo-700 disabled:opacity-50 transition-colors shadow-sm"
        >
          <Sparkles size={18} />
          <span>{generateMutation.isLoading ? 'Generating...' : 'Auto-Generate with AI'}</span>
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Editor */}
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Subject</label>
            <input 
              type="text" 
              value={subject} 
              onChange={(e) => setSubject(e.target.value)}
              className="w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 text-sm"
            />
          </div>
          <div>
            <div className="flex justify-between items-end mb-1">
              <label className="block text-sm font-medium text-slate-700">Body Content</label>
              <span className="text-xs text-slate-400">Use {'{{name}}'} for personalization</span>
            </div>
            <textarea 
              rows={12}
              value={body} 
              onChange={(e) => setBody(e.target.value)}
              className="w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 text-sm font-mono"
            />
          </div>
          <div className="flex space-x-3">
            <button 
              onClick={() => setIsPreview(!isPreview)}
              className="flex-1 bg-slate-100 text-slate-700 px-4 py-2 rounded-md font-medium text-sm hover:bg-slate-200 transition-colors"
            >
              {isPreview ? 'Hide Preview' : 'Show Live Preview'}
            </button>
            <button 
              onClick={handleSend}
              disabled={sendMutation.isLoading || !meeting.members?.length}
              className="flex-1 flex justify-center items-center space-x-2 bg-blue-600 text-white px-4 py-2 rounded-md font-medium text-sm hover:bg-blue-700 disabled:opacity-50 transition-colors"
            >
              <Send size={16} />
              <span>{sendMutation.isLoading ? 'Sending...' : `Send to ${meeting.members?.length || 0} Members`}</span>
            </button>
          </div>
        </div>

        {/* Live Preview Pane */}
        {isPreview && (
          <div className="bg-slate-50 border border-slate-200 rounded-xl overflow-hidden flex flex-col shadow-inner">
            <div className="bg-slate-200 px-4 py-2 border-b border-slate-300 flex items-center space-x-2 text-slate-600 text-sm">
              <Mail size={16} />
              <span className="font-medium">Inbox Preview</span>
            </div>
            <div className="p-6 flex-1 overflow-y-auto">
              <div className="mb-4 pb-4 border-b border-slate-200">
                <p className="text-xl font-bold text-slate-800">{subject || 'No Subject'}</p>
                <p className="text-sm text-slate-500 mt-1">To: John Doe (john.doe@example.com)</p>
              </div>
              <div 
                className="text-slate-700 text-sm whitespace-pre-wrap leading-relaxed"
                dangerouslySetInnerHTML={{ __html: body ? body.replace(/{{name}}/gi, 'John Doe') : '<p class="text-slate-400 italic">Generate or write content to see preview.</p>' }}
              />
            </div>
          </div>
        )}
      </div>

    </div>
  );
};

export default InvitationTab;
