import React, { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import api from '../../../api/axios';
import toast from 'react-hot-toast';
import { FileText, Download, CheckCircle, XCircle } from 'lucide-react';

const ReportsTab = ({ meeting }) => {
  const [isPreviewMode, setIsPreviewMode] = useState(false);
  const [reportData, setReportData] = useState(null);
  const queryClient = useQueryClient();

  const docs = meeting.documents || [];
  const hasMinutes = docs.some(d => d.type === 'MINUTES');
  const hasPhotos = docs.some(d => d.type === 'PHOTO');
  const isReady = hasMinutes && hasPhotos;

  const generateMutation = useMutation({
    mutationFn: async () => {
      const { data } = await api.post(`/reports/meetings/${meeting.id}/generate-report`);
      return data;
    },
    onSuccess: (data) => {
      setReportData(data);
      setIsPreviewMode(true);
      toast.success('Report structure generated by AI successfully');
    },
    onError: () => toast.error('Failed to generate report structure')
  });

  const downloadPdfMutation = useMutation({
    mutationFn: async () => {
      const baseUrl = import.meta.env.VITE_API_URL.replace(/\/api$/, '');
      window.open(`${baseUrl}/uploads/Report-${meeting.id}.pdf`, '_blank');
    },
    onSuccess: () => {
      toast.success('PDF Downloaded successfully');
      queryClient.invalidateQueries(['meeting', meeting.id]);
    },
    onError: () => toast.error('Failed to download PDF')
  });

  return (
    <div className="p-6 bg-white rounded-b-xl border border-t-0 border-slate-200">
      
      {!isPreviewMode ? (
        <div className="max-w-2xl mx-auto py-8">
          <div className="text-center mb-8">
            <div className="w-16 h-16 bg-blue-50 text-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
              <FileText size={32} />
            </div>
            <h3 className="text-2xl font-bold text-slate-800">Generate Final Report</h3>
            <p className="text-slate-600 mt-2">Our AI will process the uploaded Minutes and Attendance data to build a structured, professional post-meeting report.</p>
          </div>

          <div className="bg-slate-50 border border-slate-200 rounded-xl p-6 mb-8 space-y-4">
            <h4 className="font-semibold text-slate-800 border-b border-slate-200 pb-2">Pre-requisite Checklist</h4>
            <div className="flex items-center justify-between">
              <span className="text-slate-600">Minutes of Meeting Uploaded</span>
              {hasMinutes ? <CheckCircle className="text-green-500" size={20} /> : <XCircle className="text-red-500" size={20} />}
            </div>
            <div className="flex items-center justify-between">
              <span className="text-slate-600">Event Photos Uploaded</span>
              {hasPhotos ? <CheckCircle className="text-green-500" size={20} /> : <XCircle className="text-red-500" size={20} />}
            </div>
            <div className="flex items-center justify-between">
              <span className="text-slate-600">Attendance Locked</span>
              {meeting.status === 'ATTENDANCE_LOCKED' || meeting.status === 'COMPLETED' || meeting.status === 'REPORT_GENERATED' ? <CheckCircle className="text-green-500" size={20} /> : <XCircle className="text-red-500" size={20} />}
            </div>
          </div>

          <button 
            onClick={() => generateMutation.mutate()}
            disabled={!isReady || generateMutation.isLoading}
            className="w-full flex justify-center items-center space-x-2 bg-indigo-600 text-white px-6 py-4 rounded-xl font-bold text-lg hover:bg-indigo-700 disabled:opacity-50 transition-colors shadow-sm"
          >
            <span>{generateMutation.isLoading ? 'AI Analyzing...' : 'Generate AI Report'}</span>
          </button>
        </div>
      ) : (
        <div className="space-y-6">
          <div className="flex justify-between items-center bg-slate-50 p-4 rounded-xl border border-slate-200">
            <h3 className="font-bold text-lg text-slate-800">Report Preview</h3>
            <div className="flex space-x-3">
              <button 
                onClick={() => setIsPreviewMode(false)}
                className="px-4 py-2 text-slate-600 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 text-sm font-medium"
              >
                Close Preview
              </button>
              <button 
                onClick={() => downloadPdfMutation.mutate()}
                disabled={downloadPdfMutation.isLoading}
                className="flex items-center space-x-2 bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-700 disabled:opacity-50"
              >
                <Download size={18} />
                <span>{downloadPdfMutation.isLoading ? 'Generating PDF...' : 'Download PDF'}</span>
              </button>
            </div>
          </div>

          <div className="border border-slate-200 p-8 rounded-xl bg-white shadow-sm max-w-4xl mx-auto prose">
            <h1 className="text-center text-2xl font-bold border-b border-slate-300 pb-4">{meeting.title} - Official Report</h1>
            
            <div className="mt-8 grid grid-cols-2 gap-4 text-sm text-slate-600">
              <p><strong>Date:</strong> {new Date(meeting.date).toLocaleDateString()}</p>
              <p><strong>Venue:</strong> {meeting.venue}</p>
              <p><strong>Total Present:</strong> {meeting.members?.filter(m => m.attendanceStatus === 'PRESENT').length || 0}</p>
            </div>

            <div className="mt-8">
              <h3 className="text-lg font-bold text-blue-900 border-b-2 border-blue-100 pb-1 inline-block mb-3">Executive Summary</h3>
              <p className="text-slate-700 leading-relaxed">{reportData?.summary || 'Summary placeholder'}</p>
            </div>
            
            <div className="mt-6">
              <h3 className="text-lg font-bold text-blue-900 border-b-2 border-blue-100 pb-1 inline-block mb-3">Key Decisions</h3>
              <p className="text-slate-700 leading-relaxed">{reportData?.decisions || 'Decisions placeholder'}</p>
            </div>

            <div className="mt-6">
              <h3 className="text-lg font-bold text-blue-900 border-b-2 border-blue-100 pb-1 inline-block mb-3">Action Items</h3>
              <p className="text-slate-700 leading-relaxed">{reportData?.actionItems || 'Action items placeholder'}</p>
            </div>

            <div className="mt-6">
              <h3 className="text-lg font-bold text-blue-900 border-b-2 border-blue-100 pb-1 inline-block mb-3">Conclusion</h3>
              <p className="text-slate-700 leading-relaxed">{reportData?.conclusion || 'Conclusion placeholder'}</p>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default ReportsTab;
